export const builderTypes = {
    ADD_INGREDIENT : 'ADD_INGREDIENT',
    REMOVE_INGREDIENT : 'REMOVE_INGREDIENT',
    GET_PRICE : 'GET_PRICE',
    CONFIRM_BURGER : 'CONFIRM_BURGER',
    DELETE_BURGER : 'DELETE_BURGER',
    RESET_RECEIPT : 'RESET_RECEIPT',
}